### ISSUE TITLE
Add INR symbol

### ISSUE THREAD

**Issue by shuklaalok7** [Nishi-Inc/billing#1]
INR symbol should get printed in the PDF.
This may require to use some font which has ₹ in it. [This link](https://github.com/bpampuch/pdfmake/wiki/Custom-Fonts---client-side) has steps to add a cutom font to use in pdfmake. The same is discussed at bpampuch/pdfmake#33.

**Comment by shuklaalok7** [comment]
Ubuntu font contains ₹. It can be downloaded from [here](http://font.ubuntu.com/).

**Comment by mpsbhat** [comment]
What is the key in ubuntu font family to add `₹` symbol? Myself used with `Ubuntu-R.ttf` font & build the vfs_fonts.js file. But no use when trying with both `₹` & `U+20B9` in typing.

**Comment by shuklaalok7** [comment]
@mpsbhat Simply use `vfs_fonts.js` file from this repository. It contains Roboto font which has ₹ symbol.

**Comment by mpsbhat** [comment]
But myself using some other fonts also in my application. Also is it possible to use UTF-8 fonts like Kannada. Tried and failed with lohit kannada, baraha & nudi fonts.

**Comment by shuklaalok7** [comment]
Make sure that those font have ₹ symbol, and you'll be able to see it on the PDF, when you use &#8377 in HTML or use ₹ (typed using shift + 4 in some indianized keyboards).

**Comment by mpsbhat** [comment]
Thank you for the information.
Is there any ways to include Kannada fonts (unicode) also?
